name: covid_vaccination
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.0
  google_fonts: ^2.0.0
  http: ^0.13.2
  lottie: ^1.0.1
  pluto_grid: 2.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  platform: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/png/
